CREATE DATABASE IF NOT EXISTS `retro_users`;
CREATE DATABASE IF NOT EXISTS `retro_games`;
CREATE DATABASE IF NOT EXISTS `retro_discounts`;
CREATE DATABASE IF NOT EXISTS `retro_schedulers`;
CREATE DATABASE IF NOT EXISTS `retro_carts`;