management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always 
  endpoints:
    web:
      exposure:
        include: '*'
is-local: false
allowed:
  paths: /oauth2/**,/swagger-ui/**,/v3/api-docs/**,/login,/home,/actuator/**,/api/v1/auth/**,/eureka/**,/api/v1/users/register
server:
  port: 8080
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: api-gateway
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8000/Retro/admin/}
#Oauth
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebook.client-id}
            client-secret: ${facebook.client-secret}
            scope: email,public_profile
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: email,profile

  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}
      password: ${REDIS_PASSWORD:mypass}
      timeout: 60000 
  config:
#    import: configserver:http://localhost:8088
    import: "optional:configserver:"
  cloud: 
    compatibility-verifier:
      enabled: false
    config:
      discovery:
        enabled: true  
        service-id: retrorealm-config-server  
      fail-fast: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: payment_route
        predicates:
        - Path=/api/v1/payment/**
        uri: lb://PAYMENT-SERVICE
        filters:
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@rateLimter}"
            key-resolver: "#{@proxyKeyResolver}"
      - id: user_route
        predicates:
        - Path=/api/v1/users/**
        uri: lb://USER-SERVICE
      - id: client_route
        predicates:
        - Path=/app/**
        uri: lb://proxy-client
      - id: game_route
        predicates:
        - Path=/api/v1/game/**
        uri: lb://game-service
        filters:
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@rateLimter}"
            key-resolver: "#{@proxyKeyResolver}"
            
      - id: cart_route
        predicates:
        - Path=/api/v1/cart/**
        uri: lb://cart-service
      # - filters:
      #   - SetPath=/
      #   id: eureka-route
      #   predicates:
      #   - Path=/eureka/home
      #   uri: http://localhost:8761
      # - id: eureka-static-route
      #   predicates:
      #   - Path=/eureka/**
      #   uri: http://localhost:8761
      - id: order-route
        predicates:
        - Path=/api/v1/order/**
        uri: lb://order-service
        filters:
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@rateLimter}"
            key-resolver: "#{@proxyKeyResolver}"
      - id: discount-route
        predicates:
        - Path=/api/v1/discount/**
        uri: lb://discount-service
        filters:
        - name: RequestRateLimiter
          args:
            rate-limiter: "#{@rateLimter}"
            key-resolver: "#{@proxyKeyResolver}"
  main:
    web-application-type: reactive 
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    enabled: true
    urls:
    - name: gateway-service
      url: /v3/api-docs
    - name: game-service
      url: /api/v1/game/v3/api-docs
#jwt 
jwt:
  header: Authorization
  secret: ${jwt.secret}
  expiration: 604800      
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
  
