# Build Stage
FROM maven:3.8.5-openjdk-17-slim AS build 

WORKDIR /RetroRealm-NotificationService

COPY pom.xml .
RUN mvn dependency:resolve
COPY src ./src

RUN mvn clean package -DskipTests


# Run Stage
FROM openjdk:17
WORKDIR /RetroRealm-NotificationService

COPY --from=build /RetroRealm-NotificationService/target/RetroRealm-NotificationService-1.0.jar /RetroRealm-NotificationService/RetroRealm-NotificationService.jar


EXPOSE ${SERVER_PORT}
ENTRYPOINT ["java", "-jar", "/RetroRealm-NotificationService/RetroRealm-NotificationService.jar", "--server.port=${SERVER_PORT}"]